Update 01-Building-Blocks.yaml

diff --git a/.github/workflows/01-Building-Blocks.yaml b/.github/workflows/01-Building-Blocks.yaml
--- a/.github/workflows/01-Building-Blocks.yaml
+++ b/.github/workflows/01-Building-Blocks.yaml
@@ -3,17 +3,19 @@ name: 01- building Blocks
 on: push
 
 jobs:
+
   echo-hello:
     runs-on: ubuntu-latest
     steps:
       - name: Say Helo
         run: echo "Hello World"
+        
   echo-goodbye:
   runs-on: ubuntu-latest
-    steps:
-      - name: Failed step
-        run: |
-            echo "I will fail"
-            exit 1
-      - name: Say goodbye
-        run: echo "Goodbye!"
+  steps:
+    - name: Failed step
+      run: |
+          echo "I will fail"
+          exit 1
+    - name: Say goodbye
+      run: echo "Goodbye!"
