Update 01-Building-Blocks.yaml

diff --git a/.github/workflows/01-Building-Blocks.yaml b/.github/workflows/01-Building-Blocks.yaml
--- a/.github/workflows/01-Building-Blocks.yaml
+++ b/.github/workflows/01-Building-Blocks.yaml
@@ -11,11 +11,11 @@ jobs:
         run: echo "Hello World"
         
   echo-goodbye:
-  runs-on: ubuntu-latest
-  steps:
-    - name: Failed step
-      run: |
-          echo "I will fail"
-          exit 1
-    - name: Say goodbye
-      run: echo "Goodbye!"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step
+        run: |
+            echo "I will fail"
+            exit 1
+      - name: Say goodbye
+        run: echo "Goodbye!"
